### ISSUE TITLE
unraid下部署docker运行提示解析配置文件「/config.json」失败

### ISSUE THREAD

**Issue by Joyist2021** [mebtte/cicada#63]
unraid的docker仅支持目录对目录方式映射，不支持  -v $HOME/cicada-config.json:/config.json:ro \ 文件对文件方式映射，可否另外出个/config.json文件放在/cicada-config/config.json下的方式，这样只需映射/cicada-config/目录到本地，就能自动读取config.json了

**Comment by Joyist2021** [comment]
报错信息

`解析配置文件「/config.json」失败
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at Object.readSync (pkg/prelude/bootstrap.js:944:32)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1079:36)
    at z (/snapshot/cicada/server.js)
    at /snapshot/cicada/server.js
    at tryCatch (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
解析配置文件「/config.json」失败
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at Object.readSync (pkg/prelude/bootstrap.js:944:32)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1079:36)
    at z (/snapshot/cicada/server.js)
    at /snapshot/cicada/server.js
    at tryCatch (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
解析配置文件「/config.json」失败
`

**Comment by mebtte** [comment]
要先在宿主机生成配置文件然后再映射, 不然 docker 会认为 `config.json` 是个目录

**Comment by Joyist2021** [comment]
要先在宿主机生成配置文件然后再映射, 不然 docker 会认为配置.json是个目录

—----
即便创建了.json文件，docker 会认为配置.json是目录

**Comment by mebtte** [comment]
我研究一下

**Comment by mebtte** [comment]
@Joyist2021 [0.76.0](https://github.com/mebtte/cicada/releases/tag/0.76.0) 已将配置文件从 `/config.json` 移至 `/config/cicada.json`, [不支持文件映射的话可以映射 `/config` 目录](https://github.com/mebtte/cicada#docker)

此外依然兼容配置文件位于 `/config.json` 直到 v1 版本
