### ISSUE TITLE
你好，请问可以安装在NAS上吗？

### ISSUE THREAD

**Issue by guxinjian666** [mebtte/cicada#78]
我想把这个系统安装在NAS上，随时随地可以听歌，可以做到吗？

**Comment by mebtte** [comment]
使用 docker 或者独立部署都可以

**Comment by guxinjian666** [comment]
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at Object.readSync (pkg/prelude/bootstrap.js:944:32)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1079:36)
    at Q (/snapshot/cicada/dist/cli.js:1:3565)
    at /snapshot/cicada/dist/cli.js:1:164041
    at tryCatch (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/snapshot/cicada/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
Can not parse config file [ /config/cicada.json

**Comment by mebtte** [comment]
提供一下 docker 的运行命令或者 docker compose 文件

**Comment by guxinjian666** [comment]
version: '3'
services:
  cicada:
    restart: always
    container_name: cicada
    image: mebtte/cicada
    ports:
      - 8000:80
    volumes:
      - /path/config.json:/config/cicada.json
      - /share/CACHEDEV2_DATA/cicada:/data

**Comment by mebtte** [comment]
`/path/config.json` 这个文件存在吗? 知了需要现在宿主创建配置文件然后映射到容器

**Comment by guxinjian666** [comment]
存在的，配置如下：
{ 


"emailHost": "smtp.163.com",
"emailUser": "XXX@163.com",
"emailPass": "*******",
"initialAdminEmail": "XXX@163.com"

}

**Comment by mebtte** [comment]
系统是否支持文件映射? 不支持文件映射的话可以使用目录映射, 类似问题 https://github.com/mebtte/cicada/issues/63
