### ISSUE TITLE
求助，请问这种报错是不是缺少依赖？

### ISSUE THREAD

**Issue by shllwxr** [mebtte/cicada#95]
[root@localhost ~]# /cicada/cicada start -c /cicada/config.json
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/pkg/1f8cc72dfb50f0c54b04dd7a709ef5ef89b2b1f3b063270646bd12c81173b2e8/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/cicada/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.5.0

**Comment by shllwxr** [comment]
GCC 版本太低造成的，已自行解决。
